# @package _global_

defaults:
  - _self_
  - data: default
  - policy: bc_transformer_policy
  - train: default
  - eval: default
  - lifelong: base
  - test: null

seed: 10000
use_wandb: true
wandb_project: "BOSS Training & Evaluation"
folder: "./libero/datasets/"
bddl_folder: null # use default path
init_states_folder: null # use default path
load_previous_model: false
device: "cuda:7"
task_embedding_format: "bert"
task_embedding_one_hot_offset: 1
pretrain: false
pretrain_model_path: ""
benchmark_name: "boss_44"
version: "0.0.0"
# yy: Do you wanna disable skill rollout eval (only do once after all training)?
is_customize_task: true
task_num_to_use: null

# BL3 related parameters

#bl3_folder: "bl3"
#bl3_mapping: "bl3.json"
#only_success: false
#ratio: 1.0

#bl3_folder: "bl3_seed10000"
#bl3_mapping: "bl3_seed10000.json"
#only_success: true
#ratio: 1.0

bl3_folder: "bl3_all"
bl3_mapping: "bl3_all.json"
only_success: true
ratio: 1.0


is_debug: true